### ISSUE TITLE
RCS and AIMBOT problem

### ISSUE THREAD

**Issue by ParanoIIa91** [avitran0/deadlocked#9]
RCS works half of the time, 1 spray straight to the target, second one full recoil and so on, also how to completely get rid of aimbot, i have check marked only RCS but autoaim kicks in randomly locking crosshair over enemies heads, which is very bad? COSMIC de, cachy os.

**Comment by avitran0** [comment]
you uncheck `enable aimbot` and check `enable rcs`. i actually forgot to implement the aimbot disable config option, but that should be resolved now. i cannot reproduce the rcs issues on my end, a video would help to diagnose. please pull the latest changes or use the latest released build.

**Comment by ParanoIIa91** [comment]
Good work my guy, it works perfectly now, even wallhack is working! My gf just tried new verion mid game but for her wallhack isint working, maybe she need to restart pc or something, gonna check that later, when she is finished with her game, but on my end now its buttery smooth experience!

**Comment by avitran0** [comment]
thanks a lot :) the overlay thing is still buggy, but this is honestly just a linux thing mostly. the c++ version might work better, but i've kinda given up on the overlay. on windows, it's easy to make a window always on top and transparent, but some wayland compositors forbid this, or don't even offer the option for security reasons.

**Comment by ParanoIIa91** [comment]
Just double checked, for her WH still doesnt work but she is on KDE, while i tried COSMIC just for fun and i believe switching between x11 and wayland does nothing, atleast it wasnt on previous version, anyways, she is already triggered, that it works for me, so yeah haha.

**Comment by ParanoIIa91** [comment]
Yeah, i was right, switching to x11, doesnt help for my gf.
